# Generated by Django 4.2.13 on 2024-06-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parque',
            name='codigo_parque',
            field=models.IntegerField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_casco',
            field=models.IntegerField(),
        ),
    ]
