# Generated by Django 4.2.13 on 2024-06-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0002_alter_parque_codigo_parque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parque',
            name='codigo_parque',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_casco',
            field=models.IntegerField(unique=True),
        ),
    ]
