# Generated by Django 4.2.13 on 2024-06-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0003_alter_parque_codigo_parque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacaciones',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
