# Generated by Django 4.2.13 on 2024-06-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0004_alter_vacaciones_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacaciones',
            old_name='estado',
            new_name='disfrutada',
        ),
    ]
