# Generated by Django 4.2.13 on 2024-06-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0005_rename_estado_vacaciones_disfrutada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacaciones',
            name='dias_totales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
