# Generated by Django 4.2.13 on 2024-06-24 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacaciones', '0011_alter_vacaciones_dias_totales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacaciones',
            options={'ordering': (['fecha_inicio'], ['usuario']), 'verbose_name': 'Vacacione', 'verbose_name_plural': 'Vacaciones'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
