# Generated by Django 5.0.6 on 2024-06-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0012_alter_vacaciones_options_remove_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacaciones',
        ),
    ]
