# Generated by Django 4.2.13 on 2024-07-25 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacaciones', '0014_vacaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacaciones',
            options={'verbose_name': 'Vacacione', 'verbose_name_plural': 'Vacaciones'},
        ),
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas', models.IntegerField()),
                ('hrs_extras', models.BooleanField(default=False)),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacaciones.brigada')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacaciones.parque')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bolsa',
                'verbose_name_plural': 'Bolsas',
            },
        ),
    ]
